config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :encounters
  resources :merchandises
  resources :transactions
  resources :recruits
  resources :alumnis
  resources :players
  resources :people
  resources :events do
    resources :attendancerecords

    resources :attendancerecords do
      member do
        get :delete
      end
    end
  end

  resources :people do
    member do
      get :delete
    end
  end

  resources :players do
    member do
      get :delete
    end
  end

  resources :recruits do
    member do
      get :delete
    end
  end

  resources :transactions do
    member do
      get :delete
    end
  end

  resources :merchandises do
    member do
      get :delete
    end
  end

  resources :events do
    member do
      get :delete
    end
  end

  resources :encounters do
    member do
      get :delete
    end
  end

  root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
end

app/models/alumni.rb
# frozen_string_literal: true

class Alumni < ApplicationRecord
end

app/controllers/alumnis_controller.rb
# frozen_string_literal: true

class AlumnisController < ApplicationController
  before_action :set_alumni, only: %i[show edit update destroy]

  # GET /alumnis or /alumnis.json
  def index
    @people = Person.all.select { |p| p.person_type == 'Alumni' }
  end
end

app/helpers/alumnis_helper.rb
# frozen_string_literal: true

module AlumnisHelper
end

app/views/alumnis/_form.html.erb
<%= form_with(model: person) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% person.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :uin %>
    <%= form.number_field :uin %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :person_type %>
    <%= form.select :person_type, options_for_select(["Player", "Alumni", "Recruit"]), value: nil %>
  </div>

  <div class="field">
    <%= form.label :dues %>
    <%= form.number_field :dues %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alumnis/index.html.erb
<nav class="navbar navCustom navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <li class="navbarLink" id="link1"><%= link_to('Home', root_path, :class => "nav-link") %></li>
      </li>
      <li class="nav-item">
        <li class="navbarLink" id="link1"><%= link_to('Players', players_path, :class => "nav-link")%></li>
      </li>
      <li class="nav-item">
        <b><li class="navbarLink" id="link2"><%= link_to('Alumnis', alumnis_path, :class => "nav-link") %></li></b>
      </li>
      <li class="nav-item">
        <li class="navbarLink" id="link2"><%= link_to('Recruits', recruits_path, :class => "nav-link") %></li>
      </li>
      <li class="nav-item">
         <li class="navbarLink" id="link1"><%= link_to('Merchandise', merchandises_path, :class => "nav-link")%></li> 
      </li>
      <li class="nav-item">
         <li class="navbarLink" id="link1"><%= link_to('Transactions', transactions_path, :class => "nav-link")%></li>
      </li>
      <li class="nav-item">
         <li class="navbarLink" id="link1"><%= link_to('Events', events_path, :class => "nav-link")%></li>
      </li>
    </ul>
    <div class="my-2 my-lg-0">
      <%= link_to('Sign Out', destroy_admin_session_path	) %>
    </div>
  </div>
</nav>
<p id="notice"><%= notice %></p>

<center>
<h3 class="display-3">Alumni</h3>

<div class="container"><table id="alumni_table" class="table table-bordered table-hover table-stripped">
  <thead>
    <tr>
      <th>UIN</th>
      <th>Name</th>
      <th>Email</th>
      <th>Phone Number</th>
      <th>Address</th>
      <th>Person Type</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
  <% @people.each do |person| %>
    <tr>
      <td><%= person.uin %></td>
      <td><%= person.name %></td>
      <td><%= person.email %></td>
      <td><%= person.phone_number %></td>
      <td><%= person.address %></td>
      <td><%= person.person_type %></td>
      <td><%= link_to 'Show', person %></td>
      <td><%= link_to 'Edit', edit_person_path(person) %></td>
      <td><%= link_to 'Delete', delete_person_path(person)%></td>
    </tr>
  <% end %>
</tbody>

  
</table></div>
</center>
<button onClick="sendEmail();" class="btn btn-primary">Send Email</button>
<%= link_to 'New Alumni', new_person_path, :class => "btn btn-primary" %>

<script>

  function sendEmail(){
    
    var emails = []
    var table = document.getElementById("alumni_table")
    var cells = table.childNodes;

    cells[3].childNodes.forEach(cell => {
      if(cell.nodeType == 1){
        console.log(cell.childNodes[5].innerText)
        emails.push(cell.childNodes[5].innerText)
      }
    })
    
    window.location.assign("mailto:"+ emails + ", ")
  }

</script>