config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :encounters
  resources :merchandises
  resources :transactions
  resources :recruits
  resources :alumnis
  resources :players
  resources :people
  resources :events do
    resources :attendancerecords

    resources :attendancerecords do
      member do
        get :delete
      end
    end
  end

  resources :people do
    member do
      get :delete
    end
  end

  resources :players do
    member do
      get :delete
    end
  end

  resources :recruits do
    member do
      get :delete
    end
  end

  resources :transactions do
    member do
      get :delete
    end
  end

  resources :merchandises do
    member do
      get :delete
    end
  end

  resources :events do
    member do
      get :delete
    end
  end

  resources :encounters do
    member do
      get :delete
    end
  end

  root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  has_many :attendancerecords, inverse_of: :event, dependent: :destroy
  has_many :players, through: :attendancerecords

  validates_associated :attendancerecords
  validates_associated :players

  validates :name, presence: true
  validates :date, presence: true
  validates :time, presence: true
  validates :address, presence: true
  validates :event_type, presence: true
  validates :score, presence: true
  validates :season, presence: true
  validates :info, presence: true
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  def delete
    @event = Event.find(params[:id])
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to events_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to events_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_path, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :info, :date, :time, :address, :event_type, :score, :season,
                                  :attendancerecord_id, :attendancetype, :note, :uin, :player_id)
  end
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :info %>
    <%= form.text_field :info %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_field :time %>
  </div>
  
  <div class="field">
    <%= form.label :event_type %>
    <%= form.select :event_type, options_for_select(["Game", "Practice", "Tournament"]), value: nil %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :season %>
    <%= form.select :season, options_for_select(["7s", "15s"]), value: nil %>
  </div>
  <div class="field">
    <%= form.label :score %>
    <%= form.text_field :score %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/delete.html.erb
<div class="event delete">
<h2>Delete Event</h2>


<%= form_for(@event, :method => 'delete') do |f| %>

  <p>Are you sure you want to permanently delete this event?</p>

<div class="container"><table class="table table-bordered table-hover table-stripped">
  <thead>
    <tr>
        <th>Name</th>
        <th>Info</th>
        <th>Date</th>
        <th>Time</th>
        <th>Type</th>
        <th>Address</th>
        <th>Season</th>
        <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @event.name %></td>
      <td><%= @event.info %></td>
      <td><%= @event.date %></td>
      <td><%= @event.time %></td>
      <td><%= @event.event_type %></td>
      <td><%= @event.address %></td>
      <td><%= @event.season %></td>
      <td><%= @event.score %></td>
    </tr>
  </tbody>
  </table></div>

  <div class="form-buttons">
    <%= f.submit("Delete Event") %>
  </div>

<% end %>
<br/>
</div>

<%= link_to('Back', events_path, :class => 'back-link') %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<nav class="navbar navCustom navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <li class="navbarLink" id="link1"><%= link_to('Home', root_path, :class => "nav-link") %></li>
      </li>
      <li class="nav-item">
        <li class="navbarLink" id="link1"><%= link_to('Players', players_path, :class => "nav-link")%></li>
      </li>
      <li class="nav-item">
        <li class="navbarLink" id="link2"><%= link_to('Alumnis', alumnis_path, :class => "nav-link") %></li>
      </li>
      <li class="nav-item">
        <li class="navbarLink" id="link2"><%= link_to('Recruits', recruits_path, :class => "nav-link") %></li>
      </li>
      <li class="nav-item">
         <li class="navbarLink" id="link1"><%= link_to('Merchandise', merchandises_path, :class => "nav-link")%></li> 
      </li>
      <li class="nav-item">
         <li class="navbarLink" id="link1"><%= link_to('Transactions', transactions_path, :class => "nav-link")%></li>
      </li>
      <li class="nav-item">
         <b><li class="navbarLink" id="link1"><%= link_to('Events', events_path, :class => "nav-link")%></li></b>
      </li>
    </ul>
    <div class="my-2 my-lg-0">
      <%= link_to('Sign Out', destroy_admin_session_path	) %>
    </div>
  </div>
</nav>
<p id="notice"><%= notice %></p>

<center>
<h3 class="display-3">Events</h3>

<div class="container"><table class="table table-bordered table-hover table-stripped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Info</th>
      <th>Date</th>
      <th>Time</th>
      <th>Type</th>
      <th>Address</th>
      <th>Season</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.info %></td>
        <td><%= event.date %></td>
        <td><%= event.time %></td>
        <td><%= event.event_type %></td>
        <td><%= event.address %></td>
        <td><%= event.season %></td>
        <td><%= event.score %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Attendance Records', event_attendancerecords_path(event) %></td>
        <td><%= link_to 'Delete', delete_event_path(event)%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</center>
<br>
<%= link_to 'New Event', new_event_path, :class => "btn btn-primary"  %>
<br>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Info:</strong>
  <%= @event.info %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.time %>
</p>

<p>
  <strong>Type:</strong>
  <%= @event.event_type %>
</p>

<p>
  <strong>Address:</strong>
  <%= @event.address %>
</p>

<p>
  <strong>Season:</strong>
  <%= @event.season %>
</p>

<p>
  <strong>Score:</strong>
  <%= @event.score %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Add Attendance Record', new_event_attendancerecord_path(@event, @attendancerecord) %> |
<%= link_to 'Back', events_path %>