config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :encounters
  resources :merchandises
  resources :transactions
  resources :recruits
  resources :alumnis
  resources :players
  resources :people
  resources :events do
    resources :attendancerecords

    resources :attendancerecords do
      member do
        get :delete
      end
    end
  end

  resources :people do
    member do
      get :delete
    end
  end

  resources :players do
    member do
      get :delete
    end
  end

  resources :recruits do
    member do
      get :delete
    end
  end

  resources :transactions do
    member do
      get :delete
    end
  end

  resources :merchandises do
    member do
      get :delete
    end
  end

  resources :events do
    member do
      get :delete
    end
  end

  resources :encounters do
    member do
      get :delete
    end
  end

  root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
end

app/models/encounter.rb
# frozen_string_literal: true

class Encounter < ApplicationRecord
  # Each encounter is linked to a recruit through
  # the recruit_id field.
  belongs_to :recruit
  validates :notes, presence: true
  validates :recruit_id, presence: true
end

app/controllers/encounters_controller.rb
# frozen_string_literal: true

class EncountersController < ApplicationController
  before_action :set_encounter, only: %i[show edit update destroy]

  # GET /encounters or /encounters.json
  def index
    # @recruits = Recruit.find(params[:id])
    # @encounters = Encounter.find(encounter_params[:notes, :recruit_id])
    @encounters = Encounter.all
    # @encounters = Encounter.includes(:recruit_id).where(recruit_id: { pending: true })
    # @encounters = Encounter.all.select { |p| p.recruit_id == @recruit }
    # @encounters = Encounter.includes(:recruits).where( recruit_id == 3)
  end

  # GET /encounters/1 or /encounters/1.json
  def show; end

  # GET /encounters/new
  def new
    @encounter = Encounter.new
  end

  # GET /encounters/1/edit
  def edit; end

  def delete
    @encounter = Encounter.find(params[:id])
  end

  # POST /encounters or /encounters.json
  def create
    @encounter = Encounter.new(encounter_params)

    respond_to do |format|
      if @encounter.save
        format.html { redirect_to encounters_url, notice: 'Encounter was successfully created.' }
        format.json { render :show, status: :created, location: @encounter }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /encounters/1 or /encounters/1.json
  def update
    respond_to do |format|
      if @encounter.update(encounter_params)
        format.html { redirect_to encounters_url, notice: 'Encounter was successfully updated.' }
        format.json { render :show, status: :ok, location: @encounter }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @encounter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encounters/1 or /encounters/1.json
  def destroy
    @encounter.destroy
    respond_to do |format|
      format.html { redirect_to encounters_url, notice: 'Encounter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_encounter
    @encounter = Encounter.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def encounter_params
    params.require(:encounter).permit(:notes, :recruit_id)
  end
end

app/helpers/encounters_helper.rb
# frozen_string_literal: true

module EncountersHelper
end

app/views/encounters/_form.html.erb
<%= form_with(model: encounter) do |form| %>
  <% if encounter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(encounter.errors.count, "error") %> prohibited this encounter from being saved:</h2>

      <ul>
        <% encounter.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :recruit_id %>
    <%= form.collection_select :recruit_id, Recruit.all.select { |p| p.person_type == 'Recruit' },:id,:name, include_blank: true %>  </div>

  <div class="field">
    <%= form.label :notes %>
    <%= form.text_area :notes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/encounters/delete.html.erb
<div class="encounter delete">
<h2>Delete Encounter</h2>


<%= form_for(@encounter, :method => 'delete') do |f| %>

  <p>Are you sure you want to permanently delete this Encounter?</p>
  
  <div class="container"><table class="table table-bordered table-hover table-stripped">
  <thead>
    <tr>
        <th>Recruit</th>
        <th>Notes</th>
        <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <% recruit = Recruit.find_by(id: @encounter.recruit_id) %>
      <td><%= recruit.name %></td>
      <td><%= @encounter.notes %></td>
    </tr>
  </tbody>
  </table>
  </div>

  <div class="form-buttons">
    <%= f.submit("Delete Encounter") %>
  </div>

<% end %>
<br/>
</div>

<%= link_to('Back', encounters_path, :class => 'back-link') %>

app/views/encounters/edit.html.erb
<h1>Editing Encounter</h1>

<%= render 'form', encounter: @encounter %>

<%= link_to 'Show', @encounter %> |
<%= link_to 'Back', recruits_path %>

app/views/encounters/index.html.erb
<p id="notice"><%= notice %></p>

<nav class="navbar navCustom navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <li class="navbarLink" id="link1"><%= link_to('Home', root_path, :class => "nav-link") %></li>
      </li>
      <li class="nav-item">
        <li class="navbarLink" id="link1"><%= link_to('Players', players_path, :class => "nav-link")%></li>
      </li>
      <li class="nav-item">
        <li class="navbarLink" id="link2"><%= link_to('Alumnis', alumnis_path, :class => "nav-link") %></li>
      </li>
      <li class="nav-item">
        <li class="navbarLink" id="link2"><%= link_to('Recruits', recruits_path, :class => "nav-link") %></li>
      </li>
      <li class="nav-item">
         <li class="navbarLink" id="link1"><%= link_to('Merchandise', merchandises_path, :class => "nav-link")%></li> 
      </li>
      <li class="nav-item">
         <li class="navbarLink" id="link1"><%= link_to('Transactions', transactions_path, :class => "nav-link")%></li>
      </li>
      <li class="nav-item">
         <b><li class="navbarLink" id="link1"><%= link_to('Events', events_path, :class => "nav-link")%></li></b>
      </li>
    </ul>
    <div class="my-2 my-lg-0">
      <%= link_to('Sign Out', destroy_admin_session_path	) %>
    </div>
  </div>
</nav>

<center>
<h1>Encounters</h1>

<div class="container"><table class="table table-bordered table-hover table-stripped">
  <thead>
    <tr>
      <th>Recruit</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @encounters.each do |encounter| %>
        <tr>
          <% recruit = Recruit.find_by(id: encounter.recruit_id) %>
          <td><%= recruit.name %></td>
          <td><%= encounter.notes %></td>
          <td><%= link_to 'Show', encounter %></td>
          <td><%= link_to 'Edit', edit_encounter_path(encounter) %></td>
          <td><%= link_to 'Delete', delete_encounter_path(encounter) %></td>
        </tr>
    <% end %>
  </tbody>
</table>
</div>

</center>
<br>

<%= link_to 'New Encounter', new_encounter_path %>
<%= link_to 'Recruits', recruits_path %>

app/views/encounters/new.html.erb
<h1>New Encounter</h1>

<%= render 'form', encounter: @encounter %>

<%= link_to 'Back', encounters_path %>

app/views/encounters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Recruit:</strong>
  <% recruit = Recruit.find_by(id: @encounter.recruit_id) %>
  <td><%= recruit.name %></td>
</p>

<p>
  <strong>Notes:</strong>
  <%= @encounter.notes %>
</p>



<%= link_to 'Edit', edit_encounter_path(@encounter) %> |
<%= link_to 'Back', recruits_path %>