config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :encounters
  resources :merchandises
  resources :transactions
  resources :recruits
  resources :alumnis
  resources :players
  resources :people
  resources :events do
    resources :attendancerecords

    resources :attendancerecords do
      member do
        get :delete
      end
    end
  end

  resources :people do
    member do
      get :delete
    end
  end

  resources :players do
    member do
      get :delete
    end
  end

  resources :recruits do
    member do
      get :delete
    end
  end

  resources :transactions do
    member do
      get :delete
    end
  end

  resources :merchandises do
    member do
      get :delete
    end
  end

  resources :events do
    member do
      get :delete
    end
  end

  resources :encounters do
    member do
      get :delete
    end
  end

  root to: 'dashboards#show'
  devise_for :admins, controllers: { omniauth_callbacks: 'admins/omniauth_callbacks' }
  devise_scope :admin do
    get 'admins/sign_in', to: 'admins/sessions#new', as: :new_admin_session
    get 'admins/sign_out', to: 'admins/sessions#destroy', as: :destroy_admin_session
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show; end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  def delete
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def transaction_params
    params.require(:transaction).permit(:transaction_date, :amount, :merchandise_id, :person_id)
  end
end

app/helpers/transactions_helper.rb
# frozen_string_literal: true

module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :transaction_date %>
    <%= form.date_select :transaction_date %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
  <%= form.label "Merch" %>
  <%= form.collection_select(:merchandise_id, Merchandise.all, :id, :item_name) %>
  </div>

  <div class="field">
  <%= form.label "Person" %>
  <%= form.collection_select(:person_id, Person.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/delete.html.erb
<div class="transaction delete">
<h2>Transaction Person</h2>


<%= form_for(@transaction, :method => 'delete') do |f| %>

  <p>Are you sure you want to permanently delete this Transaction?</p>
  
<div class="container"><table class="table table-bordered table-hover table-stripped">
  <thead>
    <tr>
        <th>Transaction date</th>
        <th>Amount</th>
        <th>Merch</th>
        <th>Person</th>
        <th>Person UIN</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @transaction.transaction_date %></td>
      <td><%= @transaction.amount %></td>
      <% merchandise = @transaction.merchandise %>
        <% if merchandise == nil %>
        <td>N/A</td>
        <% else %>
        <td><%= merchandise.item_name %></td>
        <% end %>
        <% person = @transaction.person %>
        <% if merchandise == nil %>
        <td>N/A</td>
        <td>N/A</td>
        <% else %>
        <td><%= person.name %></td>
        <td><%= person.uin %></td>
        <% end %>
    </tr>
  </tbody>
  </table></div>

  <div class="form-buttons">
    <%= f.submit("Delete Person") %>
  </div>

<% end %>
<br/>
</div>

<%= link_to('Back', transactions_path, :class => 'back-link') %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<nav class="navbar navCustom navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <li class="navbarLink" id="link1"><%= link_to('Home', root_path, :class => "nav-link") %></li>
      </li>
      <li class="nav-item">
        <li class="navbarLink" id="link1"><%= link_to('Players', players_path, :class => "nav-link")%></li>
      </li>
      <li class="nav-item">
        <li class="navbarLink" id="link2"><%= link_to('Alumnis', alumnis_path, :class => "nav-link") %></li>
      </li>
      <li class="nav-item">
        <li class="navbarLink" id="link2"><%= link_to('Recruits', recruits_path, :class => "nav-link") %></li>
      </li>
      <li class="nav-item">
         <li class="navbarLink" id="link1"><%= link_to('Merchandise', merchandises_path, :class => "nav-link")%></li> 
      </li>
      <li class="nav-item">
         <b><li class="navbarLink" id="link1"><%= link_to('Transactions', transactions_path, :class => "nav-link")%></li></b>
      </li>
      <li class="nav-item">
         <li class="navbarLink" id="link1"><%= link_to('Events', events_path, :class => "nav-link")%></li>
      </li>
    </ul>
    <div class="my-2 my-lg-0">
      <%= link_to('Sign Out', destroy_admin_session_path	) %>
    </div>
  </div>
</nav>
<p id="notice"><%= notice %></p>

<center>
<h3 class="display-3">Transactions</h3>

<div class="container"><table class="table table-bordered table-hover table-stripped">
  <thead>
    <tr>
      <th>Transaction date</th>
      <th>Amount</th>
      <th>Merch</th>
      <th>Person name</th>
      <th>Person UIN</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.transaction_date %></td>
        <td><%= transaction.amount %></td>
        <% merchandise = transaction.merchandise %>
        <% if merchandise == nil %>
        <td>N/A</td>
        <% else %>
        <td><%= merchandise.item_name %></td>
        <% end %>
        <% person = transaction.person %>
        <% if merchandise == nil %>
        <td>N/A</td>
        <td>N/A</td>
        <% else %>
        <td><%= person.name %></td>
        <td><%= person.uin %></td>
        <% end %>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Delete', delete_transaction_path(transaction)%></td>
      </tr>
      </tr>
    <% end %>
  </tbody>
</table></div>
</center>


<br>

<%= link_to 'New Transaction', new_transaction_path, :class => "btn btn-primary" %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transaction date:</strong>
  <%= @transaction.transaction_date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Merchandise ID:</strong>
  <%= @transaction.merchandise_id %>
</p>

<p>
  <strong>Person ID:</strong>
  <%= @transaction.person_id %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>